---
# tasks file for configure-root/configure-zsh
- name: Shell | Install ZSH
  include_role:
    name: toolbox
    tasks_from: install-packages
  vars:
    packages:
      - zsh

- name: Shell | Install Oh My Zsh
  git:
    accept_hostkey: yes
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    dest: /usr/local/share/oh-my-zsh

- name: Configure .zshenv file
  lineinfile:
    path: /root/.zshenv
    line: 'ZSH=/usr/local/share/oh-my-zsh'
    create: true
    state: present

- name: Shell | Initialize ZSH environment
  file:
    src: /root/.dotfiles/zshrc
    dest: /root/.zshrc
    state: link
    force: true

- name: Shell | Set ZSH as shell for root user
  user:
    name: root
    shell: /usr/bin/zsh
