---
# tasks file for debian-host/configure-user
- name: Configure user "{{ user.name }}"
  user:
    name: "{{ user.name }}"
    comment: "{{ user.gecos }}"
    shell: "{{ user.shell }}"

- name: Set password for user "{{ user.name }}"
  user:
    name: "{{ user.name }}"
    password: "{{ user.password }}"
  when: user.password is defined

- name: Set sudo for "{{ user.name }}"
  user:
    name: "{{ user.name }}"
    groups: sudo
    append: true
  when: user.sudo is defined and user.sudo

- name: Add keys for user "{{ user.name }}"
  authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ user.authorized_keys }}"
  when: user.authorized_keys is defined

