---
# tasks file for debian-host/configure-glusterfs
- name: Install prerequisites packages for GlusterFS
  include_role:
    name: toolbox
    tasks_from: install-packages
  vars:
    packages: apt-transport-https

- name: Add key for GlusterFS repository
  apt_key:
    url: 'http://download.gluster.org/pub/gluster/glusterfs/{{ glusterfs_version }}/rsa.pub'
    state: present

- name: Add GlusterFS repository
  apt_repository:
    repo: 'deb http://download.gluster.org/pub/gluster/glusterfs/{{  glusterfs_version }}/LATEST/Debian/stretch/amd64/apt stretch main'
    filename: 'glusterfs'
    state: present

- name: Install GlusterFS packages
  include_role:
    name: toolbox
    tasks_from: install-packages
  vars:
    packages: "glusterfs-{{ glusterfs_node.type }}"

- include_role:
    name: debian-host
    tasks_from: create-mountpoint
  vars:
    mountpoint: "{{ volume.mountpoint }}"
    dev: "{{ glusterfs_node.master }}:{{ volume.src }}"
    fs: glusterfs
    opts: "_netdev,no-root-squash=on,backup-volfile-servers={{ glusterfs_node.slaves | join (':') }}"
    automount: "{{ volume.automount }}"
  with_items: "{{ mountpoints }}"
  loop_control:
    loop_var: volume
  when: volume.fs == 'glusterfs'
