---
# tasks file for debian-host/configure-network
- name: "configure-network : check if bridge-utils is needed"
  set_fact:
    need_bridge: true
  loop: "{{ network_interfaces }}"
  loop_control:
    loop_var: interface
  when: interface.type == "bridge"
  tags:
    - always

- name : "configure-network : run debian-host/toolbox/install-packages tasks"
  include_role:
    name: debian-host
    tasks_from: toolbox/install-packages
  vars:
    packages:
      - bridge-utils
  when: need_bridge | default (false) == true
  tags:
    - always

- name: "configure-network : apply /network/interfaces configuration"
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  tags:
    - always