---
# tasks file for debian-host/configure-disk
# vars
# disk:
#   name: device name (ex: /dev/sdb)
#   partitions:
#     fs: partition file system (ext4, lvm, swap)
#
- name: "configure-disk@{{ disk.name }} : preparing disk '{{ disk.name }}'"
  stat:
    path: "{{ disk.name }}"
  register: stat_disk
  tags:
    - always

- name: "debian-host : configure-disk@{{ disk.name }} : run debian-host/configure-disk/configure-partition on disk {{ disk.name }} tasks"
  include_role:
    name: debian-host
    tasks_from: "configure-disk/configure-partition-{{ partition.fs }}"
  with_items: "{{ disk.partitions }}"
  loop_control:
    loop_var: partition
  when: stat_disk.stat.exists == true and disk.partitions is defined
  tags:
    - always


