---
# tasks file for debian-physical-host/create-mountpoint
- name: "configure-mountpoint@{{ dev }}@{{ mountpoint }} : create mountpoint"
  file:
    path: "{{ mountpoint }}"
    state: directory
  tags:
    - always

- name: "configure-mountpoint@{{ dev }}@{{ mountpoint }} : add mountpoint in /etc/fstab"
  mount:
    path: "{{ mountpoint }}"
    src: "{{ dev }}"
    fstype: "{{ fs }}"
    opts: "{{ opts | default ('defaults')}}"
    state: present
  tags:
    - always

- name: "configure-mountpoint@{{ dev }}@{{ mountpoint }} : mount filesystem"
  mount:
    path: "{{ mountpoint }}"
    src: "{{ dev }}"
    fstype: "{{ fs }}"
    opts: "{{ opts | default ('defaults') }}"
    state: mounted
  when: automount is defined and automount
  tags:
    - always



