---
# tasks file for debian-host
# Upgrade system
- name: "debian-host : run {{ ansible_distribution | lower }}-host/toolbox/update-system tasks"
  include_role:
    name: "debian-host"
    tasks_from: toolbox/update-system
  tags:
    - upgrade

# Install default packages
- name: "debian-host : run debian-host/toolbox/install-packages tasks"
  include_role:
    name: "debian-host"
    tasks_from: toolbox/install-packages
  vars:
    packages: "{{ default_packages | default ([])}} + {{ host_packages | default ([])}}"
  tags:
    - upgrade

# Install packages with pip
- name: "debian-host : run toolbox/install-pip-packages tasks"
  include_role:
    name: toolbox
    tasks_from: install-pip-packages
  vars:
    packages: "{{ default_pip_packages | default ([])}} + {{ host_pip_packages | default ([])}}"
  tags:
    - upgrade

- name: "debian-host : run debian-host/configure-os tasks"
  include_role:
    name: debian-host
    tasks_from: configure-os
  tags:
    - os-configuration

# Configure hard drives
- name: "debian-host : run debian-host/configure-disk tasks"
  include_role:
    name: debian-host
    tasks_from: configure-disk
  with_items: "{{ disks }}"
  loop_control:
    loop_var: disk
  when: disks is defined
  tags:
    - disks-configuration

# Configure network interfaces
- name: "debian-host : run debian-host/configure-network tasks"
  include_role:
    name: debian-host
    tasks_from: configure-network
  when: network_interfaces is defined
  tags:
    - network-configuration

# Configure users
- name: "debian-host : run debian-host/configure-users"
  include_role:
    name: debian-host
    tasks_from: configure-users
  with_items: "{{ default_users | default([]) }} + {{ users | default([]) }}"
  loop_control:
    loop_var: user
  tags:
    - users-configuration
