---
# tasks file for debian-host
# Upgrade system
- name: Run toolbox/update-system
  include_role:
    name: toolbox
    tasks_from: update-system

# Install default packages
- name: Run toolbox/install-packages
  include_role:
    name: toolbox
    tasks_from: install-packages
  vars:
    packages: "{{ default_packages|default([]) }} + {{ host_packages|default([]) }}"

# Configure locales
- name: Run debian-host/set-locale
  include_role:
    name: debian-host
    tasks_from: set-locale

# Configure users
- name: Run debian-host/configure-users
  include_role:
    name: debian-host
    tasks_from: configure-users
  with_items: "{{ default_users|default([]) }} + {{ users|default([]) }}"
  loop_control:
    loop_var: user
