---
# tasks file for debian-physical-host/prepare-device/configure-partition-lvm
- name: "debian-host : configure-disk@{{ disk.name }} : lvm : run debian-host/toolbox/install-packages tasks"
  include_role:
    name: debian-host
    tasks_from: toolbox/install-packages
  vars:
    packages:
      - parted
      - lvm2
  tags:
    - always

- name: "configure-disk@{{ disk.name }} : lvm@{{ disk.name }}{{ partition.index }} : create partition"
  parted:
    device: "{{ disk.name }}"
    number: "{{ partition.index }}"
    state: present
    unit: MB
    part_start: "{{ partition.start }}"
    part_end: "{{ partition.end }}"
    flags: [ lvm ]
  tags:
    - always

# Configure lvm pool
- name: "debian-host : configure-disk@{{ disk.name }} : lvm@{{ disk.name }}{{ partition.index }} : run tasks from configure-disk/lvm/configure-pool"
  include_role:
    name: debian-host
    tasks_from: configure-disk/lvm/configure-pool
  when: lvm_pool is defined
  tags:
    - always


