---
# tasks file for debian-host/configure-disk/configure-partition-swap
- name: "configure-disk@{{ disk.name }} : swap@{{ device.name }}{{ partition.index }} : create swap partition"
  parted:
    device: "{{ device.name }}"
    number: "{{ partition.index }}"
    state: present
    unit: MB
    part_start: "{{ partition.start }}"
    part_end: "{{ partition.end }}"
  when: create_partition | default (true) == true
  tags:
    - always

- name: "configure-disk@{{ disk.name }} : swap@{{ device.name }}{{ partition.index }} : stat swap"
  shell: "blkid -s TYPE -o value {{ device.name }}{{ partition.index }}"
  ignore_errors: yes
  register: stat_swap
  tags:
    - always

- name: "configure-disk@{{ disk.name }} : swap@{{ device.name }}{{ partition.index }} : check if swap is already activated"
  shell: swapon --noheadings --show=name
  register: swapon
  tags:
    - always

# Create swap
- name: "configure-disk@{{ disk.name }} : swap@{{ device.name }}{{ partition.index }} : create swap fs"
  shell: "mkswap {{ device.name }}{{ partition.index }}"
  when: stat_swap.stdout == ''
  tags:
    - always

- name: "configure-disk@{{ disk.name }} : swap@{{ device.name }}{{ partition.index }} : activate swap"
  shell: "swapon {{ device.name }}{{ partition.index }}"
  when: swapon.stdout == ""
  tags:
    - always

- name: "configure-disk@{{ disk.name }} : swap@{{ device.name }}{{ partition.index }} : add swapfile to /etc/fstab"
  mount:
    name: none
    src: "{{ device.name }}{{ partition.index }}"
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present
  tags:
    - always
