---
# tasks file for configure-users/configure-zsh
- name: "[configure-user:{{ user.name }}] Shell:zsh | Install packages"
  include_role:
    name: toolbox
    tasks_from: install-packages
  vars:
    packages:
      - zsh

- name:  "[configure-user:{{ user.name }}] Shell:zsh | Install Oh My Zsh"
  git:
    accept_hostkey: yes
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    dest: /usr/local/share/oh-my-zsh
  when: user.ohmyzsh is defined and user.ohmyzsh == true

- name:  "[configure-user:{{ user.name }}] Shell:zsh | Configure Oh My Zsh in .zshenv file"
  lineinfile:
    path: "{{ user.home }}/.zshenv"
    line: 'ZSH=/usr/local/share/oh-my-zsh'
    create: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: present
  when: user.ohmyzsh is defined and user.ohmyzsh == true
  become_user: "{{ user.name }}"

- name: "[configure-user:{{ user.name }}] Shell:zsh | Check for resources/users/{{ user.name }}/zshrc"
  local_action: stat path="{{ playbook_dir }}/resources/users/{{ user.name }}/zshrc"
  register: stat_user_zshrc

- name:  "[configure-user:{{ user.name }}] Shell:zsh | Install user configuration"
  copy:
    src: "{{ playbook_dir }}/resources/users/{{ user.name }}/zshrc"
    dest: "{{ user.home }}/.zshrc"
    force: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  when: stat_user_zshrc.stat.exists == true

- name: "[configure-user:{{ user.name }}] Shell:zsh | Check for resources/users/{{ user.name }}/functions"
  local_action: stat path="{{ playbook_dir }}/resources/users/{{ user.name }}/functions"
  register: stat_user_functions

- name:  "[configure-user:{{ user.name }}] Shell:zsh | Install user functions"
  copy:
    src: "{{ playbook_dir }}/resources/users/{{ user.name }}/functions/"
    dest: "{{ user.home }}/.zsh.functions"
    force: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  when: stat_user_functions.stat.exists == true

- name:  "[configure-user:{{ user.name }}] Shell:zsh | Set ZSH as user shell"
  user:
    name: "{{ user.name }}"
    shell: /usr/bin/zsh
