---
# tasks file for configure-users/configure-trmux
- name: "debian-host : configure-user@{{ user.name }} : tmux : run debian-host/toolbox/install-packages tasks"
  include_role:
    name: debian-host
    tasks_from: toolbox/install-packages
  vars:
    packages:
      - tmux
  tags:
    - always

- name: "configure-user@{{ user.name }} : tmux : check for resources/users/{{ user.name }}/tmux.conf"
  local_action: stat path="{{ playbook_dir }}/resources/users/{{ user.name }}/tmux.conf"
  register: stat_user_tmux
  tags:
    - always

- name: "configure-user@{{ user.name }} : tmux : install user configuration"
  copy:
    src: "{{ playbook_dir }}/resources/users/{{ user.name }}/tmux.conf"
    dest: "{{ user.home }}/.tmux.conf"
    force: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  when: stat_user_tmux.stat.exists == true
  tags:
    - always

- name: "configure-user@{{ user.name }} : tmux : tweak ssh server to accept TMUX variable"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AcceptEnv'
    line: "AcceptEnv LANG LC_* TMUX"
  notify: restart ssh service
  tags:
    - always
