---
# tasks file for configure-users/configure-bash
- name: "[configure-user:{{ user.name }}] Shell:bash | Check for resources/users/{{ user.name }}/bashrc"
  local_action: stat path="{{ playbook_dir }}/resources/users/{{ user.name }}/bashrc"
  register: stat_user_bashrc

- name: "[configure-user:{{ user.name }}] Shell:bash | Install user configuration"
  copy:
    src: "{{ playbook_dir }}/resources/users/{{ user.name }}/bashrc"
    dest: "{{ user.home }}/.bashrc"
    force: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  when: stat_user_bashrc.stat.exists == true
