---
# tasks file for debian-physical-host/prepare-device/lvm/configure-pool
- name: "configure-disk@{{ disk.name }} : lvm@{{ disk.name }}{{ partition.index }}@{{ lvm_pool.name }} : create volume group '{{ lvm_pool.name }}'"
  lvg:
    vg: "{{ lvm_pool.name }}"
    pvs: "{{ lvm_pool.device }}"
    state: present
  tags:
    - always

# Configure logical volume
- name: "debian-host : configure-disk@{{ disk.name }} : lvm@{{ disk.name }}{{ partition.index }}@{{ lvm_pool.name }} : run debian-host/configure-disk/lvm/configure-volume tasks"
  include_role:
    name: debian-host
    tasks_from: configure-disk/lvm/configure-volume
  with_items: "{{ lvm_pool.datasets }}"
  loop_control:
    loop_var: volume
  tags:
    - always



