---
# tasks file for debian-physical-host/prepare-device/lvm/configure-pool
# Configure logical volume
- name: "configure-disk@{{ disk.name }} : lvm@{{ disk.name }}{{ partition.index }}@{{ lvm_pool.name }}/{{ volume.name }} : create logical volume '{{ lvm_pool.name }}/{{ volume.name }}'"
  lvol:
    vg: "{{ lvm_pool.name }}"
    lv: "{{ volume.name }}"
    size: "{{ volume.size }}"
  tags:
    - always

- name: "debian-host : configure-disk@{{ disk.name }} : lvm@{{ disk.name }}{{ partition.index }}@{{ lvm_pool.name }}/{{ volume.name }} : run configure-disk/configure-partition-{{ volume.type }} tasks"
  include_role:
    name: debian-host
    tasks_from: "configure-disk/configure-partition-{{ volume.type }}"
  vars:
    create_partition: false
    device:
      name: "/dev/{{ lvm_pool.name }}"
    partition:
      index: "/{{ volume.name }}"
      automount: "{{ volume.automount | default (false) }}"
      mountpoint: "{{ volume.mountpoint | default (None)}}"
  when: volume.type is defined
  tags:
    - always





