---
# tasks file for debian-host/configure-cloud-instance
- name: Disable predictable network interface names
  template:
    src: grub.j2
    dest: /etc/default/grub
  notify: update grub configuration

- name: Disable resolvconf update by DHCP
  copy:
    src: nodnsupdate
    dest: /etc/dhcp/dhclient-enter-hooks.d/nodnsupdate
    mode: u=rwx,g=rx,o=rx

- name: "Set hostname to '{{ hostname | default(inventory_hostname_short) }}'"
  lineinfile:
    path: /etc/hostname
    regexp: "^.*$"
    line: "{{ hostname }}"
  when: hostname is defined

- name: Apply new hostname
  shell: hostname "{{ hostname }}"
  when: hostname is defined

