---
# tasks file for debian--host/configure-hosts/configure-server
- name: Disable predictable network interface names
  template:
    src: grub.j2
    dest: /etc/default/grub
  notify: update grub configuration

- name: "Set hostname to '{{ hostname | default(inventory_hostname_short) }}'"
  lineinfile:
    path: /etc/hostname
    regexp: "^.*$"
    line: "{{ hostname }}"
  when: hostname is defined

- name: "Set hostname to '{{ hostname | default(inventory_hostname_short) }}'"
  lineinfile:
    path: /etc/hostname
    regexp: "^.*$"
    line: "{{ hostname }}"
  when: hostname is defined

- name: Apply new hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined
